# Generated by Django 4.2.1 on 2023-05-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_academicyears_course_teachers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('year', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active'), ('Finished', 'Finished'), ('Not Finished', 'Not Finished')], max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.DeleteModel(
            name='Academicyears',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Unenrolled', 'Unenrolled'), ('Finished', 'Finished'), ('Not Finished', 'Not Finished')], max_length=100, null=True),
        ),
    ]
