# Generated by Django 4.2.1 on 2023-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_course_code_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active'), ('Finished', 'Finished'), ('Not Finished', 'Not Finished')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.FloatField(null=True),
        ),
    ]
