# Generated by Django 4.2.1 on 2023-05-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active'), ('Finished', 'Finished'), ('Not Finished', 'Not Finished')], max_length=100, null=True),
        ),
    ]
